[package]
name = "road_intersection"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37.0", features = ["image", "ttf"] }
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
